import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export async function tryOnGarment(personImageBase64: string, garmentImageBase64: string, garmentMimeType: string): Promise<string> {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: personImageBase64,
              mimeType: 'image/jpeg',
            },
          },
          {
            inlineData: {
              data: garmentImageBase64,
              mimeType: garmentMimeType,
            },
          },
          {
            text: 'Take the person from the first image and the clothing item from the second image. Realistically and seamlessly overlay the clothing onto the person\'s body. The clothing should fit naturally on their torso. Preserve the background from the first image. Only output the final composed image.',
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to generate virtual try-on image.");
  }
}